ARDUINO_DIR=/home/weictr/opt/arduino/arduino-1.8.13/
ARDMK_DIR=Arduino-Makefile
AVR_TOOLS_DIR=/usr
BOARD_SUB=atmega328old
BOARD_TAG=nano
MONITOR_PORT=/dev/ttyUSB0
MONITOR_BAUDRATE=9600

ARDUINO_LIBS=SoftwareSerial Adafruit_NeoPixel-1.8.0
USER_LIB_PATH=./lib/

AVRDUDE      = /usr/bin/avrdude
AVRDUDE_CONF = /etc/avrdude.conf

include $(ARDMK_DIR)/Arduino.mk
